### ISSUE TITLE
Använda Sass

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Vastra-Gotalandsregionen/oppna-program-deprecated#72]
```
Saas är ett CSS-verktyg för att strukturera och kompilera CSS på ett bra och 
effektivt sätt. Vi vill använda detta i arbetet med utveckling av EPiServer.
```

Original issue reported on code.google.com by `rfc.oppn...@gmail.com` on 8 May 2015 at 2:49

**Comment by hansgyllensten** [comment]
Sas - accepted
Accepteras som standard
Vi hänvisar i första hand till att använda VGRs stilguide 
http://vastra-gotalandsregionen.github.io/vgr-styleguide/

**Comment by marcusosterberg** [comment]
Språkpolisen justerade det till Sass:
https://en.wikipedia.org/wiki/Sass_%28stylesheet_language%29
