### ISSUE TITLE
Använda Compass

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Vastra-Gotalandsregionen/oppna-program-deprecated#73]
```
Compass är ett ramverk byggt på sass. Compass erbjuder användbara funktioner 
för css3, typografi. Compass används i första hand för att slippa repetera 
kod som istället finns som mixins eller funktioner i compass. Tex rundande 
hör med stöd för alla webbläsare. @include border-radius;
```

Original issue reported on code.google.com by `rfc.oppn...@gmail.com` on 8 May 2015 at 2:50

**Comment by hansgyllensten** [comment]
Compass - deprecated 
Accepteras endast efter godkännande av VGRs arkitekturledning.
Vi hänvisar i första hand till att använda VGRs stilguide 
http://vastra-gotalandsregionen.github.io/vgr-styleguide/
