### ISSUE TITLE
Användning av GitLab inom VGR

### ISSUE THREAD

**Issue by u1239** [Vastra-Gotalandsregionen/oppna-program-deprecated#77]
En instans av GitLab finns installerad inom VGR IT och har tydligen börjat användas. Vi inom ICC skulle vilja ha besked om det är i linje med VGRs strategi att använda GitLab.
Om så är fallet är vi också mycket intresserade av eventuella riktlinjer för användandet som framtagits.

**Comment by patrikbjork** [comment]
Hej,

För VGR är det fritt fram för det team som vill använda GitLab-servern. Det är bara att logga in och skapa upp projekt. Så här långt finns inga gemensamma riktlinjer utan är fritt att använda så som respektive team anser passar dem. Om ni är intresserade av att formalisera riktlinjer, eller har andra idéer, är ni välkomna att ta initiativ till diskussion. Ni är också välkomna att höra av er om ni undrar något annat specifikt.

mvh,
Patrik Björk

**Comment by hansgyllensten** [comment]
Approved.
Återkom med förslag på gemensamma  riktlinjer
Hans Gyllensten
